### ISSUE TITLE
질문드립니다.

### ISSUE THREAD

**Issue by somefood** [pangyosim/pizzapr0ject#6]
안녕하세요 판교님,

너무나도 잘 만든 코드 잘 보았습니다.
우연히 둘러보다가 몇 가지만 개선하면 더 훌륭한 플젝이 될거 같아 이렇게 염치불고하고 
몇 가지 제안을 드리고자 합니다.

1. 루트디렉토리에 .gitignore 추가

.idea나 target 같은 폴더는 git에 올라갈 필요가 없을거 같습니다. 다른 개발자분과 개발 환경도 다르고, 빌드를 할 때마다 target도 변경이 일어날테니까 말이죠.

내가 사용하는 스택들을 입력하면 그에 맞게 추가해주는 사이트인데, 참고해서 원격 레포에 올라간 항목들을 제거하면 좋을거 같습니다! :)
[참고](https://www.toptal.com/developers/gitignore)

2. application.properties 관리하기

target에 있는 application.properties 파일을 보았습니다. 지금은 DB를 내린거 같다만, 사실 이러한 보안 정보를 public 한 곳에 올리는 것은 위험요소가 늘어나는 형태입니다. private 한 레포지토리가 아닌 경우엔 보안정보는 삭제해주시기 바랍니다. 많은 경우에 application을 개발용, 운영용으로 분리하는데 spring boot profile을 검색해서 dev용 prod 용으로 나눠보면 좋을거 같습니다~!

우선은 이 두개만 수정해보시면 좋을거 같네요 ㅎㅎ
궁금한 점은 편히 댓글 부탁드립니다~!

**Comment by pangyosim** [comment]
안녕하세요 석주님.
먼저 저희 프로젝트에 제안 주셔서 감사합니다.
덕분에 더 좋은 코드를 만들 수 있는 기회가 생겨좋네요🙂
1. 참고해주신 사이트 확인하여, 루트디렉터리에 .gitignore에 해당 파일 제외하여 커밋할 수 있게 설정완료했습니다.
2. application.properties 파일이 target 폴더에 있는 거 확인 후 제거완료하였습니다.

또한, 주신 의견대로  spring profile로 dev prod 포트 나눠서 작업 해보려 합니다.
계속해서 업데이트 예정이니, 언제든지 편하게 제안 주셔도 됩니다.
감사합니다.
